from cs50 import SQL
import sqlite3

db = SQL("sqlite:///game_database.db")

first_actor = [
    {"name": "Tom Cruise", "id": 500},
    {"name": "Scarlett Johansson", "id": 1245},
    {"name": "Leonardo DiCaprio", "id": 6193},
    {"name": "Emma Stone", "id": 54693},
    {"name": "Brad Pitt", "id": 287},
    {"name": "Meryl Streep", "id": 112},
    {"name": "Robert Downey Jr.", "id": 3223},
    {"name": "Chris Hemsworth", "id": 74568},
    {"name": "Natalie Portman", "id": 524},
    {"name": "Angelina Jolie", "id": 11701},
    {"name": "Will Smith", "id": 1315},
    {"name": "Johnny Depp", "id": 1196},
    {"name": "Matt Damon", "id": 1191},
    {"name": "Julia Roberts", "id": 1510},
    {"name": "Keanu Reeves", "id": 4537},
    {"name": "Tom Hanks", "id": 31},
    {"name": "Dwayne Johnson", "id": 8292},
    {"name": "Ryan Reynolds", "id": 522},
    {"name": "Chris Pratt", "id": 9366},
    {"name": "Joaquin Phoenix", "id": 1198},
    {"name": "Zendaya", "id": 1529499},
    {"name": "Cate Blanchett", "id": 227},
    {"name": "Charlize Theron", "id": 525},
    {"name": "Denzel Washington", "id": 347},
    {"name": "Matthew McConaughey", "id": 4958},
    {"name": "Morgan Freeman", "id": 61},
    {"name": "Harrison Ford", "id": 2},
    {"name": "Al Pacino", "id": 33},
    {"name": "Robert De Niro", "id": 123},
    {"name": "Anne Hathaway", "id": 552},
    {"name": "Michelle Williams", "id": 1305},
    {"name": "Renee Zellweger", "id": 2762},
    {"name": "Benedict Cumberbatch", "id": 133},
    {"name": "Matthew McConaughey", "id": 4958},
    {"name": "Jude Law", "id": 350},
    {"name": "Jessica Chastain", "id": 457},
    {"name": "Emma Watson", "id": 1265},
    {"name": "Hugh Jackman", "id": 322},
    {"name": "James McAvoy", "id": 2749},
    {"name": "Rachel McAdams", "id": 1024},
    {"name": "Salma Hayek", "id": 1267},
    {"name": "Mark Ruffalo", "id": 3024},
    {"name": "Will Ferrell", "id": 468},
    {"name": "Gal Gadot", "id": 1190},
    {"name": "Ryan Gosling", "id": 124},
    {"name": "Samuel L. Jackson", "id": 424},
    {"name": "Jada Pinkett Smith", "id": 22192},
    {"name": "Tessa Thompson", "id": 1431386},
    {"name": "Julia Louis-Dreyfus", "id": 14982},
    {"name": "Sofia Vergara", "id": 506},
    {"name": "Eddie Murphy", "id": 537},
    {"name": "Melissa McCarthy", "id": 3891},
    {"name": "Vince Vaughn", "id": 572},
    {"name": "Michael B. Jordan", "id": 106095},
    {"name": "Hugh Grant", "id": 61},
    {"name": "Kerry Washington", "id": 6072},
    {"name": "Chris Evans", "id": 1685},
    {"name": "Emma Thompson", "id": 216},
    {"name": "Tom Hardy", "id": 4920},
    {"name": "Mark Wahlberg", "id": 3103},
    {"name": "Ralph Fiennes", "id": 4516},
    {"name": "Beryl Reid", "id": 199302},
    {"name": "Tina Fey", "id": 1074},
    {"name": "Cameron Diaz", "id": 4422},
    {"name": "Jason Bateman", "id": 111},
    {"name": "Ryan Reynolds", "id": 522},
    {"name": "Keira Knightley", "id": 241},
    {"name": "Meryl Streep", "id": 112},
    {"name": "Matt Smith", "id": 68861},
    {"name": "David Tennant", "id": 1403},
    {"name": "Ben Affleck", "id": 1091},
    {"name": "Chris Rock", "id": 1000},
    {"name": "Bradley Cooper", "id": 3887},
    {"name": "Mila Kunis", "id": 1049},
    {"name": "Sacha Baron Cohen", "id": 883},
    {"name": "Zoe Saldana", "id": 5740},
    {"name": "Natalie Dormer", "id": 361},
    {"name": "Gillian Anderson", "id": 1342},
    {"name": "Daniel Radcliffe", "id": 1312},
    {"name": "Tom Hiddleston", "id": 1184},
    {"name": "Carrie Fisher", "id": 3812},
    {"name": "Orlando Bloom", "id": 4247},
    {"name": "James Franco", "id": 1836},
    {"name": "Maggie Smith", "id": 376},
    {"name": "Daniel Craig", "id": 547},
    {"name": "Michelle Pfeiffer", "id": 739},
    {"name": "Olivia Colman", "id": 3123},
    {"name": "Jodie Comer", "id": 1939884},
    {"name": "Florence Pugh", "id": 1813563},
    {"name": "Paul Rudd", "id": 19604},
    {"name": "Dwayne Johnson", "id": 8292},
    {"name": "Ben Stiller", "id": 210},
    {"name": "John Boyega", "id": 278458},
    {"name": "Zac Efron", "id": 2279},
    {"name": "Chris Pine", "id": 6425}
]


for actor in first_actor:
    db.execute("INSERT OR IGNORE INTO starting_actors (id, name) VALUES (?, ?)", (actor['id'], actor['name']))


conn.commit()
